www/models/Order.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property int $user_id
 * @property int $meal_id
 * @property int $status
 * @property int $bread_id
 * @property string $size
 * @property int $should_baked
 * @property int $taste_id
 * @property int $sauce_id
 * @property string $extras
 * @property string $created_at
 * @property int $rate
 *
 * @property Bread $bread
 * @property Meal $meal
 * @property Sauce $sauce
 * @property Taste $taste
 * @property User $user
 * @property OrderVegetable[] $orderVegetables
 * @property Vegetable[] $vegetables
 */
class Order extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'meal_id', 'size', 'should_baked'], 'required'],
            [['user_id', 'meal_id', 'status', 'bread_id', 'should_baked', 'taste_id', 'sauce_id'], 'integer'],
            [['size', 'extras'], 'string'],
            [['created_at'], 'safe'],
            [
                ['bread_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Bread::class,
                'targetAttribute' => ['bread_id' => 'id'],
            ],
            [
                ['meal_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Meal::class,
                'targetAttribute' => ['meal_id' => 'id'],
            ],
            [
                ['sauce_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Sauce::class,
                'targetAttribute' => ['sauce_id' => 'id'],
            ],
            [
                ['taste_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => Taste::class,
                'targetAttribute' => ['taste_id' => 'id'],
            ],
            [
                ['user_id'],
                'exist',
                'skipOnError' => true,
                'targetClass' => User::class,
                'targetAttribute' => ['user_id' => 'id'],
            ],
        ];
    }

    /**
     * @param array $data
     * @param null $formName
     * @return bool
     * @throws \yii\base\InvalidConfigException
     */
    public function load($data, $formName = null)
    {
        $scope = $formName === null ? $this->formName() : $formName;
        $data = $data[$scope];

        if (empty($this->user_id)) {
            $this->user_id = Yii::$app->user->getId();
        }

        if ($data['should_baked'] === null) {
            $data['should_baked'] = 0;
        }

        return parent::load($data, '');
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'meal_id' => 'Meal ID',
            'status' => 'Status',
            'bread_id' => 'Bread ID',
            'size' => 'Size',
            'should_baked' => 'Should Baked',
            'taste_id' => 'Taste ID',
            'sauce_id' => 'Sauce ID',
            'extras' => 'Extras',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBread()
    {
        return $this->hasOne(Bread::class, ['id' => 'bread_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeal()
    {
        return $this->hasOne(Meal::class, ['id' => 'meal_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSauce()
    {
        return $this->hasOne(Sauce::class, ['id' => 'sauce_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTaste()
    {
        return $this->hasOne(Taste::class, ['id' => 'taste_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderVegetables()
    {
        return $this->hasMany(OrderVegetable::class, ['order_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVegetables()
    {
        return $this->hasMany(Vegetable::class, ['id' => 'vegetable_id'])->viaTable('order_vegetable',
            ['order_id' => 'id']);
    }
}

www/controllers/OrderController.php
<?php

namespace app\controllers;

use app\filters\OpenedMealFilter;
use app\models\Meal;
use app\models\Order;
use app\services\OrderService;
use Yii;
use yii\base\Module;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * @var OrderService
     */
    private $orderService;

    public function __construct(string $id, Module $module, array $config = [], OrderService $orderService)
    {
        parent::__construct($id, $module, $config);
        $this->orderService = $orderService;
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            [
                'class' => OpenedMealFilter::class,
                'only' => ['create', 'update'],
                'returnUrl' => '/order',
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'create-page'],
                        'roles' => ['createOrder'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'update', 'view', 'update-page', 'rate'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['delete', 'open', 'close'],
                        'roles' => ['adminChanges'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Order::find();
        $authUser = Yii::$app->user;
        if (!$authUser->can('adminChanges')) {
            $query = $query->where(['user_id' => $authUser->getId()]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws ForbiddenHttpException
     */
    public function actionView($id)
    {
        $order = $this->findModel($id);

        if (!$this->isHassAccessToOrder($order)) {
            throw new ForbiddenHttpException('You has no access for this order!');
        }

        return $this->render('view', [
            'model' => $order,
        ]);
    }

    protected function isHassAccessToOrder(Order $order)
    {
        return Yii::$app->user->can('updateOwnOrder', ['order' => $order]) ||
            Yii::$app->authManager->getAssignment('admin', Yii::$app->user->getId());
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws \yii\base\InvalidConfigException
     * @throws \Throwable
     */
    public function actionCreate()
    {
        $model = new Order();

        /**
         * @var $meal Meal
         */
        $meal = Meal::find()->where(['status' => 1])->one();

        $postData = Yii::$app->request->post();
        $postData['Order']['meal_id'] = $meal->id;
        $postData['Order']['status'] = 1;

        $isLoadModel = $model->load($postData);
        if ($isLoadModel && $model->save()) {
            $vegetables = $postData['Order']['vegetables'];
            $this->orderService->linkVegetables($model, $vegetables);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->showErrors($model);
    }

    /**
     * @param null $id
     * @return string
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionCreatePage($id = null)
    {
        if ($id) {
            $model = $this->findModel($id);
            if (!$this->isHassAccessToOrder($model)) {
                throw new ForbiddenHttpException('You has no access for copied order!');
            }
        } else {
            $model = new Order();
        }

        /**
         * @var $meal Meal
         */
        $meal = Meal::find()->where(['status' => 1])->one();

        $availableChoices = $this->orderService->getAvailableChoices($meal);
        $availableChoices['model'] = $model;

        return $this->render('create', $availableChoices);
    }

    /**
     * @param $id
     * @param $rate
     * @return \yii\web\Response
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     */
    public function actionRate($id, $rate)
    {
        if ($rate < 1 || $rate > 5) {
            throw new BadRequestHttpException();
        }

        $model = $this->findModel($id);
        if (!Yii::$app->user->can('updateOwnOrder', ['order' => $model])) {
            throw new ForbiddenHttpException('You has no access to rate the order');
        }

        $model->rate = $rate;
        $model->save();

        return $this->redirect('/order');
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionOpen($id)
    {
        $model = $this->findModel($id);
        $model->status = 1;
        $model->save();

        return $this->redirect('/order');
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionClose($id)
    {
        $model = $this->findModel($id);
        $model->status = 0;
        $model->save();

        return $this->redirect('/order');
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     * @throws ForbiddenHttpException
     */
    public function actionUpdatePage($id)
    {
        $model = $this->findModel($id);

        if (!$this->isHassAccessToOrder($model)) {
            throw new ForbiddenHttpException('You has no access for this order!');
        }

        if ($model->status === 0 && !Yii::$app->user->can('adminChanges')) {
            Yii::$app->session->addFlash('error', 'Sorry, this order has been closed!');
            return $this->redirect('/order');
        }

        /**
         * @var $meal Meal
         */
        $meal = $model->meal;
        $availableChoices = $this->orderService->getAvailableChoices($meal);
        $availableChoices['model'] = $model;

        return $this->render('update', $availableChoices);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \yii\base\InvalidConfigException
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!$this->isHassAccessToOrder($model)) {
            throw new ForbiddenHttpException('You has no access for this order!');
        }

        if ($model->status === 0 && !Yii::$app->user->can('adminChanges')) {
            Yii::$app->session->addFlash('error', 'Sorry, this order has been closed!');
            return $this->redirect('/order');
        }

        $postData = Yii::$app->request->post();

        $isLoadModel = $model->load($postData);
        if ($isLoadModel && $model->save()) {
            $model->unlinkAll('vegetables', true);

            $vegetables = $postData['Order']['vegetables'];
            $this->orderService->linkVegetables($model, $vegetables);

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->showErrors($model);
    }

    /**
     * @param Order $model
     * @return \yii\web\Response
     */
    protected function showErrors(Order $model)
    {
        $errors = $model->getErrorSummary(true);
        foreach ($errors as $error) {
            Yii::$app->session->addFlash('error', $error);
        }

        return $this->redirect(['/order']);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

www/views/order/_form.php
<?php

use dosamigos\multiselect\MultiSelect;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">
    <?php if ($availableBreads) { ?>

        <?= $form->field($model, 'bread_id')->dropDownList($availableBreads) ?>

    <?php } ?>

    <?= $form->field($model, 'size')->dropDownList($availableSizes) ?>

    <?php if ($availableBake) { ?>

        <?= $form->field($model, 'should_baked')->dropDownList($yesNo) ?>

    <?php } ?>

    <?php if (!empty($availableTastes)) { ?>

        <?= $form->field($model, 'taste_id')->label('Taste')->dropDownList($availableTastes) ?>

    <?php } ?>

    <?php if (!empty($availableSauces)) { ?>

        <?= $form->field($model, 'sauce_id')->label('Sauce')->dropDownList($availableSauces) ?>

    <?php } ?>

    <?php if (!empty($availableExtras)) { ?>

        <?= $form->field($model, 'extras')->dropDownList($availableExtras) ?>

    <?php } ?>

    <?php if (!empty($availableVegetables)) { ?>

        <?= $form->field($model, 'vegetables')->widget(MultiSelect::class, [
            'data' => $availableVegetables,
            'options' => ['multiple' => 'multiple'],
        ]) ?>

    <?php } ?>
  <div class="form-group">
      <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
  </div>

    <?php ActiveForm::end(); ?>

</div>

www/views/order/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Create Order';
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">
    <?php $form = ActiveForm::begin(['action' => '/order/create']); ?>

  <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', compact(
        'model',
        'form',
        'availableBreads',
        'availableTastes',
        'availableVegetables',
        'availableSauces',
        'availableBake',
        'availableExtras',
        'availableSizes',
        'yesNo'
    )) ?>

</div>

www/views/order/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Orders';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

  <h1><?= Html::encode($this->title) ?></h1>

  <p>
      <?= Html::a('Create Order', ['create-page'], ['class' => 'btn btn-success']) ?>
  </p>


    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'user_id',
                'label' => 'User name',
                'value' => function ($data) {
                    return $data->user->name;
                },
            ],
            [
                'attribute' => 'meal_id',
                'label' => 'Meal name',
                'value' => function ($data) {
                    return $data->meal->name;
                },
            ],
            [
                'attribute' => 'status',
                'label' => 'Status',
                'value' => function ($data) {
                    return \app\models\Enums\OpenedClosed::getName($data->status);
                },
            ],
            'created_at',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete} {copy}',
                'buttons' => [
                    'update' => function ($url, $data) {
                        $url = \yii\helpers\Url::toRoute(['order/update-page', 'id' => $data->id], true);
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url);
                    },
                    'copy' => function ($url, $data, $key) {
                        $url = \yii\helpers\Url::toRoute(['order/create-page', 'id' => $data->id], true);
                        return Html::a('<span class="glyphicon glyphicon-copy"></span>', $url);
                    },
                ],
            ],
            [
                'label' => 'Open/Close',
                'format' => 'raw',
                'value' => function ($data) {
                    return Html::a(
                        $data->status === 1 ? 'Close' : 'Open',
                        ['/order/' . ($data->status === 1 ? 'close' : 'open'), 'id' => $data->id],
                        [
                            'title' => 'Open',
                        ]
                    );
                },
            ],
            [
                'label' => 'Rate',
                'format' => 'raw',
                'value' => function ($data) {
                    $html = '';
                    for ($i = 1; $i <= 5; $i++) {
                        $glyphiconStar = 'glyphicon-star-empty';
                        if ($i <= $data->rate) {
                            $glyphiconStar = 'glyphicon-star';
                        }

                        $url = \yii\helpers\Url::toRoute(['order/rate', 'id' => $data->id, 'rate' => $i], true);
                        $html .= Html::a("<span class=\"glyphicon $glyphiconStar\"></span>", $url);
                    }
                    return $html;
                },
            ],
        ],
    ]); ?>

</div>

www/views/order/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Update Order: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-update">
    <?php $form = ActiveForm::begin(['action' => ['/order/update', 'id' => $model->id]]); ?>

  <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', compact(
        'model',
        'form',
        'availableBreads',
        'availableTastes',
        'availableVegetables',
        'availableSauces',
        'availableBake',
        'availableExtras',
        'availableSizes',
        'yesNo'
    )) ?>

</div>

www/views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="order-view">

  <h1><?= Html::encode($this->title) ?></h1>

  <p>
      <?= Html::a('Update', ['update-page', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
      <?= Html::a('Delete', ['delete', 'id' => $model->id], [
          'class' => 'btn btn-danger',
          'data' => [
              'confirm' => 'Are you sure you want to delete this item?',
              'method' => 'post',
          ],
      ]) ?>
  </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'user_id',
                'label' => 'User name',
                'value' => function ($data) {
                    return $data->user->name;
                },
            ],
            [
                'attribute' => 'meal_id',
                'label' => 'Meal name',
                'value' => function ($data) {
                    return $data->meal->name;
                },
            ],
            [
                'attribute' => 'status',
                'label' => 'Status',
                'value' => function ($data) {
                    return \app\models\Enums\OpenedClosed::getName($data->status);
                },
            ],
            [
                'attribute' => 'bread',
                'label' => 'Bread',
                'value' => function ($data) {
                    return $data->bread->name;
                },
            ],
            [
                'attribute' => 'size',
                'label' => 'Size',
                'value' => function ($data) {
                    return \app\models\Enums\Sizes::getName($data->size);
                },
            ],
            [
                'attribute' => 'should_baked',
                'label' => 'Should baked',
                'value' => function ($data) {
                    return \app\models\Enums\YesNo::getName($data->should_baked);
                },
            ],
            [
                'attribute' => 'taste',
                'label' => 'Taste',
                'value' => function ($data) {
                    return $data->taste->name;
                },
            ],
            [
                'attribute' => 'sauce',
                'label' => 'Sauce',
                'value' => function ($data) {
                    return $data->sauce->name;
                },
            ],
            [
                'attribute' => 'extras',
                'label' => 'Extras',
                'value' => function ($data) {
                    return \app\models\Enums\Extras::getName($data->extras);
                },
            ],
            [
                'attribute' => 'vegetables',
                'label' => 'Vegetables',
                'value' => function (\app\models\Order $data) {
                    return \app\helpers\StringHelper::getJoinedNames($data->vegetables);
                },
            ],
            [
                'attribute' => 'created_at',
                'label' => 'Created date',
            ],
        ],
    ]) ?>

</div>